package tienda.model.dao;

import tienda.model.Cliente;
import tienda.qualifiers.DAOJdbc;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.enterprise.context.Dependent;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

@Dependent  //Elegible for Dependency Injection
@DAOJdbc
public class ClienteDAOJDBC implements ClienteDAO, Serializable {
    private static final String dbTable="Clientes";
    //private static final String[] autoField={"id"}; //Autogenerated field for new records
    //private static String connPoolName="jdbc/tiendaOnline";
    //private static final String connPoolName="java:/comp/env/jdbc/gestClub";  //Tomcat
    //private static String connPoolName="jdbc/gestClub";               //Glassfish
    private static final String SQL_BUSCAID="SELECT * FROM Clientes where nick=?";
    private static final String SQL_BUSCATODOS="SELECT * FROM Clientes";
    private static final String SQL_CREA="INSERT INTO Clientes (nick,nombre,dni,correo,clave) VALUES (?,?,?,?,?)";
    private static final String SQL_ACTUALIZA="UPDATE Clientes set NOMBRE=?, DNI=?,CORREO=?, CLAVE=? WHERE nick=?";
    private static final String SQL_BORRA="DELETE FROM Clientes WHERE nick=?";
    private static final String SQL_LOGIN = "SELECT * FROM Clientes WHERE (nombre=? AND clave=?)";

  @Resource(lookup = "jdbc/tiendaOnline")
     private DataSource ds;
    
    public ClienteDAOJDBC() {
//        if (ds==null) {
//            try {
//                Context context = new InitialContext();
//                ds = (DataSource) context.lookup(connPoolName);
//            } catch (NamingException ex) {
//                Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
//            }
//        }
    }
    
    /**Recupera un Cliente del registro actual del RS (MAPPING)*/
    private static Cliente clienteMapper(ResultSet rs) throws SQLException {
        Cliente c;
        c=new Cliente(  rs.getString("NICK"),
                        rs.getString("NOMBRE"),
                        rs.getString("DNI"),
                        rs.getString("CORREO"),
                        rs.getString("CLAVE")
        );
        return c;
    }  
   
    @Override
    public Cliente buscaId(String nick) {
        Cliente c=null;
        try (Connection conn=ds.getConnection();
             PreparedStatement stmn=conn.prepareStatement(SQL_BUSCAID)) {
            stmn.setString(1,nick);
            try( ResultSet rs=stmn.executeQuery()) {
                rs.next();
                c=clienteMapper(rs);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return c;
    }

    
    

    @Override
    public List<Cliente> buscaTodos() {
        List<Cliente> l=new ArrayList<>();
        try (Connection conn=ds.getConnection();
            Statement stmn=conn.createStatement();
            ResultSet rs=stmn.executeQuery(SQL_BUSCATODOS);
        ){
            while (rs.next()) {
                l.add(clienteMapper(rs));
            }                
        } catch (Exception ex) {
            Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return l;
    }

    @Override
    public boolean crea(Cliente c) {
        boolean result=false;
        try (Connection conn=ds.getConnection();
            PreparedStatement stmn=conn.prepareStatement(SQL_CREA);
        ){
            stmn.setString(1, c.getNick());
            stmn.setString(2,c.getNombre());
            stmn.setString(3,c.getDni());
            stmn.setString(4,c.getCorreo());
            stmn.setString(5,c.getClave());
            stmn.executeUpdate();
            /*
            
            
            PREGUNTAR !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            
            
            */
            try (ResultSet rs=stmn.getGeneratedKeys()) {
                //Get autogenerated field value
                if (rs!=null && rs.next()) {
                    String nuevoNick=rs.getString(1); //RS has only one field with key value
                    c.setNick(nuevoNick);
                }
            } catch (Exception ex) {
                Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return result;
    }

    @Override
    public boolean guarda(Cliente c) {
        boolean result=false;
        try (Connection conn=ds.getConnection();
            PreparedStatement stmn=conn.prepareStatement(SQL_ACTUALIZA);
        ){
            stmn.setString(1,c.getNombre());
            stmn.setString(2,c.getDni());
            stmn.setString(3,c.getCorreo());
            stmn.setString(4,c.getClave());
            stmn.setString(5,c.getNick());
            result=(stmn.executeUpdate()==1);
        } catch (Exception ex) {
            Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return result;
    }
    
    @Override    
    public boolean borra(String nick) {
        boolean result=false;
        try (Connection conn=ds.getConnection();
            PreparedStatement stmn=conn.prepareStatement(SQL_BORRA);
        ){
            stmn.setString(1,nick);
            result=(stmn.executeUpdate()==1);
        } catch (Exception ex) {
            Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }         
        return result;
    }
    
    
    
    
    @Override
    public Cliente logIn(String nombre, String clave){
        Cliente c = null;
        try (Connection conn = ds.getConnection();
                PreparedStatement stmn=conn.prepareStatement(SQL_LOGIN)){
            stmn.setString(1, nombre);
            stmn.setString(2,clave);
            try( ResultSet rs=stmn.executeQuery()) {
                rs.next();
                c = clienteMapper(rs);                
            }
        }catch(SQLException ex) {
            Logger.getLogger(ClienteDAOJDBC.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }
        return c;
    }
    
    
}
// Closing recourses and catching exceptions correctly JDK<7!!!!
//		Connection con = null;
//		Statement stmt = null;
//		ResultSet rs = null;
//		try {
//			con = ds.getConnection();
//			stmt = con.createStatement();
//			rs = stmt.executeQuery("select empid, name from Employee");
//			while(rs.next()){
//				System.out.println("Employee ID="+rs.getInt("empid")+", Name="+rs.getString("name"));
//			}
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}finally{
//				try {
//					if(rs != null) rs.close();
//					if(stmt != null) stmt.close();
//					if(con != null) con.close();
//				} catch (SQLException e) {
//					e.printStackTrace();
//				}
//		}
//	}